package com.puzzlesolver.core.puzzle.terminal

import com.puzzlesolver.core.image.GrayImage
import com.puzzlesolver.core.puzzle.GlyphClassifier
import com.puzzlesolver.core.puzzle.TemplateGlyphClassifier

/**
 * The digit templates for the terminal wall, shipped as a resource.
 *
 * Everywhere else in this app, glyph templates are *rendered* at startup from the
 * platform's own font, and [com.puzzlesolver.core.puzzle.TemplateGlyphClassifier] and
 * `GlyphAtlas` both explain why: for a puzzle printed in an unknown typeface, a template
 * drawn by the same engine at the same resolution beats a shipped bitmap. That argument
 * does not apply here, and following it anyway was measurably wrong.
 *
 * The wall's digits are not printed in an unknown typeface. They are a split-flap
 * display in a fixed installation, so the typeface is *known hardware* -- the same on
 * every visit, at every distance, for every player. And a generic sans-serif is a poor
 * stand-in for it: measured over 1860 digits from the reference clip, templates rendered
 * from a Helvetica-like face misread 2, while ones from Segoe UI misread 46 -- almost
 * all of them a three read as an eight, because that face draws a flat-topped three and
 * this wall draws a round one. Which of those the platform happens to supply is not
 * something to leave to chance in a room with one attempt at a round.
 *
 * So these templates are the wall's own digits: every legible glyph in the reference
 * clip, normalised exactly as the reader normalises one and averaged per digit. That
 * makes the typeface a solved problem rather than a gamble: with the platform's font
 * the fixture came back with six digits wrong, and with these it comes back clean.
 *
 * They are regenerated by `TerminalTemplateBuilder`, which runs the real reader so the
 * templates cannot drift from the normalisation. If the wall in your room turns out to
 * use a different display, that tool and a clip of it are the whole of the fix.
 */
object TerminalDigits {

    /** Ten [GlyphNormaliser.SIZE]-square templates stacked into one PGM, 0 at the top. */
    const val RESOURCE = "terminal-digits.pgm"

    /**
     * How well a glyph must correlate before it is called a digit.
     *
     * Higher than the printed-puzzle default of 0.55, because these templates are the
     * wall's own: a real digit scores 0.93 or better against them, so 0.55 would not be
     * a threshold at all, it would be an invitation for a smear of glare to be read as a
     * seven. The lowest score over the 93 legible glyphs of the fixture is 0.93, which
     * leaves this a long way clear of anything real.
     */
    const val MIN_CORRELATION = 0.70f

    /**
     * How far ahead of the runner-up the winner must be to be trusted.
     *
     * Lower than the printed-puzzle default of 0.06, and for a reason worth writing
     * down: ten digits drawn at one size in one frame all correlate highly with each
     * other whatever they are -- five against eight is 0.92 between these templates --
     * so genuine margins here are narrow even when the answer is not in doubt. Measured
     * over the 93 legible glyphs of the fixture the narrowest correct margin is 0.058, a
     * zero over an eight. At 0.06 every one of those would be flagged as ambiguous,
     * which is not a safety net, it is a broken confidence number.
     */
    private const val MIN_MARGIN = 0.03f

    val templates: List<TemplateGlyphClassifier.Template> by lazy { load() }

    /**
     * A classifier for wall digits.
     *
     * One orientation, not the usual four. Four exists for the canvas, whose up is only
     * known modulo a quarter turn; a camera frame's up is known exactly, and trying the
     * other three orientations there cannot make a reading better -- a six upside down
     * is a nine -- only worse.
     */
    fun classifier(): GlyphClassifier =
        TemplateGlyphClassifier(templates, MIN_CORRELATION, MIN_MARGIN, orientations = 1)

    private fun load(): List<TemplateGlyphClassifier.Template> {
        val size = GlyphNormaliser.SIZE
        val stream = TerminalDigits::class.java.classLoader?.getResourceAsStream(RESOURCE)
            ?: error("$RESOURCE is missing from the core resources")
        stream.use { input ->
            fun token(): String {
                val sb = StringBuilder()
                var c = input.read()
                while (c == ' '.code || c == '\n'.code || c == '\r'.code || c == '\t'.code) c = input.read()
                if (c == '#'.code) {
                    while (c != '\n'.code && c > 0) c = input.read()
                    return token()
                }
                while (c > 0 && c != ' '.code && c != '\n'.code && c != '\r'.code && c != '\t'.code) {
                    sb.append(c.toChar())
                    c = input.read()
                }
                return sb.toString()
            }
            require(token() == "P5") { "$RESOURCE is not a binary PGM" }
            val w = token().toInt()
            val h = token().toInt()
            token()                                     // maxval
            require(w == size && h == size * DIGITS) { "$RESOURCE is ${w}x$h, expected ${size}x${size * DIGITS}" }
            val data = ByteArray(w * h)
            var read = 0
            while (read < data.size) {
                val n = input.read(data, read, data.size - read)
                if (n <= 0) break
                read += n
            }
            require(read == data.size) { "$RESOURCE is short: $read of ${data.size}" }

            return (0 until DIGITS).map { d ->
                val image = GrayImage(size, size)
                System.arraycopy(data, d * size * size, image.data, 0, size * size)
                TemplateGlyphClassifier.Template(d, image)
            }
        }
    }

    private const val DIGITS = 10
}
